export const styles ={
    container:{
    backgroundColor:"fff",
    flex:1,
    alignItems: "center"
    },
    titulo:{
        fontSize:30,
        textAlign:"center"
    },
    TextInput:{
        backgroundColor:"#ececec",
        padding:15,
        width:150,
        borderRadius:6,
        fontSize:20
    },
    form:{
        marginTop:40
    },
    resultado:{
        fontSize:30
    },
    btn:{
        backgroundColor:"#2993c8",
        with:150,
        borderRadius:50,
        padding:15,
        alignItems:"center",
        marginTop:10
     },
     btnText:{
        color:"#fff",
        fontSize:20
     },
        img:{
           with: 150,
           height:30
        }
}